### ISSUE TITLE
classcast exception on maven deploy SDE-Locations

### ISSUE THREAD

**Issue by guiguilechat** [guiguilechat/EveOnline#4]
java.lang.ClassCastException: fr.guiguilechat.eveonline.model.sde.load.fsd.universe.Constellation cannot be cast to fr.guiguilechat.eveonline.model.sde.load.fsd.universe.Constellation
    at fr.guiguilechat.eveonline.model.sde.load.fsd.universe.Constellation.load (Constellation.java:32)

**Comment by OkYk** [comment]
Encountered the same issue, intermittent, will take a look as well.
Will likely require to manipulate classloader.

**Comment by guiguilechat** [comment]
bypass it by recalling mvn with -rf just after.
Only happen on sde-locations.
